language: python

python:
  - "3.6"
  
env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings

  matrix:
    - DJANGO_VERSION=2.0.5
    - DJANGO_VERSION=2.1.7
    # - DJANGO_VERSION=1.11.13
  
install:
  - pip install Django==$DJANGO_VERSION coverage
  - python manage.py makemigrations
  
script: 
  - coverage run --source='shortener' manage.py test

after_script:
  - pip install coveralls
  - coveralls
