# Generated by Django 2.2.10 on 2020-06-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20190528_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlprofile',
            name='default_lifespan',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='urlprofile',
            name='max_concurrent_urls',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
